Repository AY2223S2-CS2103-F11-3/tp, pull requests merged in 2023-03, with the labels that each got.

#49 Vaccination feature
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/vms/model/vaccination/VaxChecker.java
  src/main/java/seedu/vms/model/vaccination/VaxRecord.java
  src/main/java/seedu/vms/model/vaccination/VaxRequirement.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/test/java/seedu/vms/model/vaccination/VaccinationCheckerTest.java
  src/test/java/seedu/vms/model/vaccination/VaccinationRecordTest.java
Labels: priority.High, type.Task

#55 Update parsing to parse common delimiter
  src/main/java/seedu/vms/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/vms/logic/parser/CliSyntax.java
  src/main/java/seedu/vms/logic/parser/patient/AddCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/EditCommandParser.java
  src/test/java/seedu/vms/logic/commands/CommandTestUtil.java
  src/test/java/seedu/vms/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/vms/logic/parser/patient/EditCommandParserTest.java
  src/test/java/seedu/vms/testutil/PersonUtil.java
Labels: priority.High, type.Task

#58 Add date only parser
  src/main/java/seedu/vms/logic/parser/ParserUtil.java
  src/test/java/seedu/vms/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Task

#64 Vaccination type basic structure
  src/main/java/seedu/vms/commons/util/FileUtil.java
  src/main/java/seedu/vms/commons/util/JsonUtil.java
  src/main/java/seedu/vms/model/vaccination/Requirement.java
  src/main/java/seedu/vms/model/vaccination/VaxChecker.java
  src/main/java/seedu/vms/model/vaccination/VaxRequirement.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeStorage.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxRequirement.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java
  src/main/java/seedu/vms/storage/vaccination/VaxTypeLoader.java
  src/main/resources/data/vaxTypes.json
  src/test/data/JsonVaxTypeTest/DefaultTypeValues.json
  src/test/data/JsonVaxTypeTest/EmptyReqSet.json
  src/test/data/JsonVaxTypeTest/MissingName.json
  src/test/data/JsonVaxTypeTest/MissingReqSet.json
  src/test/data/JsonVaxTypeTest/MissingReqType.json
  src/test/data/JsonVaxTypeTest/NonJsonFormat.json
  src/test/data/JsonVaxTypeTest/NonStringInReqSet.json
  src/test/data/JsonVaxTypeTest/UnknownReqType.json
  src/test/data/JsonVaxTypeTest/ValidMultipleTypes.json
  src/test/data/JsonVaxTypeTest/ZeroTypes.json
  src/test/java/seedu/vms/model/vaccination/RequirementTest.java
  src/test/java/seedu/vms/model/vaccination/VaccinationCheckerTest.java
  src/test/java/seedu/vms/model/vaccination/VaccinationRecordTest.java
  src/test/java/seedu/vms/model/vaccination/VaxCheckerTest.java
  src/test/java/seedu/vms/model/vaccination/VaxRecordTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTestingUtil.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeStorageTest.java
  src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java
Labels: priority.High, type.Task

#66 Move potato user to NFR
  docs/DeveloperGuide.md
Labels: type.Bug

#73 Integrate VaxTypeManager to Logic
  src/main/java/seedu/vms/MainApp.java
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java
  src/main/java/seedu/vms/storage/Storage.java
  src/main/java/seedu/vms/storage/StorageManager.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java
  src/main/java/seedu/vms/storage/vaccination/VaxTypeLoader.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeManagerTest.java
  src/test/java/seedu/vms/storage/StorageManagerTest.java
  src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java
  src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Labels: priority.High, type.Task

#91 Add VaxRecordKey class
  src/main/java/seedu/vms/model/vaccination/VaxRecordKey.java
  src/test/java/seedu/vms/model/vaccination/VaxRecordKeyTest.java
Labels: priority.High, type.Task

#95 Add read and write functionalities for VaxType
  src/main/java/seedu/vms/MainApp.java
  src/main/java/seedu/vms/commons/util/FileUtil.java
  src/main/java/seedu/vms/commons/util/JsonUtil.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/vaccination/Requirement.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/main/java/seedu/vms/storage/Storage.java
  src/main/java/seedu/vms/storage/StorageManager.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxRequirement.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java
  src/main/java/seedu/vms/storage/vaccination/JsonVaxTypeStorage.java
  src/main/java/seedu/vms/storage/vaccination/VaxTypeLoader.java
  src/main/java/seedu/vms/storage/vaccination/VaxTypeStorage.java
  src/test/java/seedu/vms/logic/LogicManagerTest.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeTest.java
  src/test/java/seedu/vms/storage/StorageManagerTest.java
  src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java
  src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Labels: priority.High, type.Task

#108 Fix ID numbering
  src/main/java/seedu/vms/commons/exceptions/LimitExceededException.java
  src/main/java/seedu/vms/model/IdDataMap.java
  src/main/java/seedu/vms/model/StorageModel.java
  src/main/java/seedu/vms/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/vms/model/IdDataMapTest.java
Labels: priority.Medium, type.Bug

#107 Basic add vaccination type command
  src/main/java/seedu/vms/logic/commands/vaccination/AddVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/ParserUtil.java
  src/main/java/seedu/vms/logic/parser/VmsParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/AddVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/vaccination/VaxName.java
  src/main/java/seedu/vms/model/vaccination/VaxRecordKey.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeAction.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/model/vaccination/VaxNameTest.java
  src/test/java/seedu/vms/model/vaccination/VaxRecordKeyTest.java
Labels: priority.High, type.Task

#98 Allows appointments to be added
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/logic/parser/CliSyntax.java
  src/main/java/seedu/vms/logic/parser/ParserUtil.java
  src/main/java/seedu/vms/logic/parser/VmsParser.java
  src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java
  src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/appointment/Appointment.java
  src/main/java/seedu/vms/model/appointment/AppointmentManager.java
  src/main/java/seedu/vms/model/appointment/ReadOnlyAppointmentManager.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
Labels: type.Story, priority.Medium, type.Epic

#110 Complete vaccination add command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/vms/logic/parser/CliSyntax.java
  src/main/java/seedu/vms/logic/parser/ParserUtil.java
  src/main/java/seedu/vms/logic/parser/vaccination/AddVaxTypeParser.java
  src/main/java/seedu/vms/model/Age.java
  src/main/java/seedu/vms/model/GroupName.java
  src/main/java/seedu/vms/model/vaccination/Requirement.java
  src/main/java/seedu/vms/model/vaccination/VaxChecker.java
  src/main/java/seedu/vms/model/vaccination/VaxRecordKey.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/main/java/seedu/vms/storage/JsonAdaptedAge.java
  src/main/java/seedu/vms/storage/JsonAdaptedGroupName.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxRequirement.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java
  src/main/java/seedu/vms/ui/TagFlowView.java
  src/main/java/seedu/vms/ui/vaccination/VaxTypeCard.java
  src/main/resources/data/vaxTypes.json
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/VaxTypeCard.fxml
  src/test/data/JsonVaxTypeTest/ValidMultipleTypes.json
  src/test/java/seedu/vms/logic/commands/vaccination/AddVaxTypeTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
  src/test/java/seedu/vms/logic/parser/ParserUtilTest.java
  src/test/java/seedu/vms/model/AgeTest.java
  src/test/java/seedu/vms/model/GroupNameTest.java
  src/test/java/seedu/vms/model/vaccination/RequirementTest.java
  src/test/java/seedu/vms/model/vaccination/VaxCheckerTest.java
  src/test/java/seedu/vms/model/vaccination/VaxRecordKeyTest.java
  src/test/java/seedu/vms/model/vaccination/VaxRecordTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTestingUtil.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeManagerTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeTest.java
  src/test/java/seedu/vms/storage/StorageManagerTest.java
  src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java
  src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Labels: priority.High, type.Task

#116 Update user guide for patient add functionality
  docs/UserGuide.md
Labels: priority.High, type.Task

#122 Change application title and icon
  copyright.txt
  src/main/java/seedu/vms/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/vms_icon_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/vms/commons/util/AppUtilTest.java
Labels: priority.Low, severity.VeryLow

#123 Remodel result message display
  .github/codecov.yml
  src/main/java/seedu/vms/MainApp.java
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/logic/commands/Command.java
  src/main/java/seedu/vms/logic/commands/CommandResult.java
  src/main/java/seedu/vms/ui/CommandBox.java
  src/main/java/seedu/vms/ui/ListViewPanel.java
  src/main/java/seedu/vms/ui/MainWindow.java
  src/main/java/seedu/vms/ui/Refreshable.java
  src/main/java/seedu/vms/ui/ResultDisplay.java
  src/main/java/seedu/vms/ui/ResultMessageBox.java
  src/main/java/seedu/vms/ui/Ui.java
  src/main/java/seedu/vms/ui/UiManager.java
  src/main/java/seedu/vms/ui/UiPart.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ResultMessageBox.fxml
  src/main/resources/view/VaxTypeCard.fxml
  src/test/java/seedu/vms/logic/LogicManagerTest.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
Labels: priority.Medium, type.Task

#141 Standardise file management
  src/main/java/seedu/vms/MainApp.java
  src/main/java/seedu/vms/commons/util/ConfigUtil.java
  src/main/java/seedu/vms/commons/util/FileUtil.java
  src/main/java/seedu/vms/commons/util/JsonUtil.java
  src/main/java/seedu/vms/storage/JsonPatientManagerStorage.java
  src/main/java/seedu/vms/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/vms/storage/PatientManagerStorage.java
  src/main/java/seedu/vms/storage/Storage.java
  src/main/java/seedu/vms/storage/StorageManager.java
  src/main/java/seedu/vms/storage/UserPrefsStorage.java
  src/main/java/seedu/vms/storage/vaccination/JsonVaxTypeStorage.java
  src/main/java/seedu/vms/storage/vaccination/VaxTypeLoader.java
  src/test/data/JsonUtilTest/InvalidJsonFormat.json
  src/test/data/JsonUtilTest/InvalidJsonMapping.json
  src/test/data/JsonUtilTest/ValidFile.json
  src/test/java/seedu/vms/commons/util/ConfigUtilTest.java
  src/test/java/seedu/vms/commons/util/JsonUtilTest.java
  src/test/java/seedu/vms/storage/JsonPatientManagerStorageTest.java
  src/test/java/seedu/vms/storage/JsonSerializablePatientManagerTest.java
  src/test/java/seedu/vms/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/vms/storage/StorageManagerTest.java
  src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java
Labels: priority.High, type.Task

#143 Fix patient card
  src/main/java/seedu/vms/ui/PatientCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/VaxTypeCard.fxml
Labels: priority.High, type.Task

#168 Fix `LogicManager` breaking on unexpected exceptions
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/logic/commands/CommandResult.java
  src/main/java/seedu/vms/ui/ResultMessageBox.java
  src/main/resources/view/DarkTheme.css
Labels: type.Bug, severity.High

#172 Complete CRUD for vaccination
  src/main/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/EditVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/vaccination/AddVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/EditVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaxTypeValueParser.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/EditVaxTypeTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
  src/test/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParserTest.java
Labels: priority.High, type.Epic

#174 Add support for Alternative Component names
  src/main/java/seedu/vms/logic/parser/VmsParser.java
  src/main/java/seedu/vms/logic/parser/patient/PatientParser.java
  src/test/java/seedu/vms/logic/parser/VmsParserTest.java
Labels: type.Story, priority.Medium

#184 Bugfix for invalid appointment duration
  src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java
  src/main/java/seedu/vms/model/appointment/Appointment.java
Labels: type.Bug, severity.Medium

#185 Fix issue where Appointment ID displayed as patient ID instead of its ID
  src/main/java/seedu/vms/ui/MainWindow.java
  src/main/java/seedu/vms/ui/appointment/AppointmentCard.java
  src/main/resources/view/AppointmentCard.fxml
Labels: type.Bug, severity.Medium

#183 Implement delete command for appointment
  src/main/java/seedu/vms/commons/core/Messages.java
  src/main/java/seedu/vms/logic/commands/appointment/DeleteCommand.java
  src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java
  src/main/java/seedu/vms/logic/parser/appointment/DeleteCommandParser.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: type.Story, priority.High, type.Task

#187 Implement edit command for appointment
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java
  src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java
  src/main/java/seedu/vms/logic/parser/appointment/EditCommandParser.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: type.Story, priority.High, type.Task

#192 Remove spacing attribute
  src/main/java/seedu/vms/logic/parser/CliSyntax.java
  src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaxTypeValueParser.java
  src/main/java/seedu/vms/model/vaccination/VaxChecker.java
  src/main/java/seedu/vms/model/vaccination/VaxRecord.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java
  src/main/java/seedu/vms/ui/vaccination/VaxTypeCard.java
  src/main/resources/data/vaxTypes.json
  src/main/resources/view/VaxTypeCard.fxml
  src/test/java/seedu/vms/logic/commands/vaccination/AddVaxTypeTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/EditVaxTypeTest.java
  src/test/java/seedu/vms/model/vaccination/VaxCheckerTest.java
  src/test/java/seedu/vms/model/vaccination/VaxRecordTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTestingUtil.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeManagerTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeTest.java
  src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java
  src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Labels: priority.High, type.Task

#180 Update CLI presentation
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
Labels: priority.Medium, type.Enhancement

#194 Fix strings
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/model/FilteredIdDataMap.java
  src/test/java/seedu/vms/logic/commands/vaccination/EditVaxTypeTest.java
  src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Labels: priority.Low, severity.Low

#205 Update CI to not run on draft PRs
  .github/workflows/gradle.yml
Labels: priority.Low, severity.Low

#211 Update UG for vaccination
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#208 Add warning to unused arguments
  src/main/java/seedu/vms/logic/CommandMessage.java
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/logic/commands/Command.java
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/logic/commands/appointment/DeleteCommand.java
  src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java
  src/main/java/seedu/vms/logic/commands/appointment/ListCommand.java
  src/main/java/seedu/vms/logic/commands/basic/ExitCommand.java
  src/main/java/seedu/vms/logic/commands/basic/HelpCommand.java
  src/main/java/seedu/vms/logic/commands/patient/AddCommand.java
  src/main/java/seedu/vms/logic/commands/patient/ClearCommand.java
  src/main/java/seedu/vms/logic/commands/patient/DeleteCommand.java
  src/main/java/seedu/vms/logic/commands/patient/EditCommand.java
  src/main/java/seedu/vms/logic/commands/patient/FindCommand.java
  src/main/java/seedu/vms/logic/commands/patient/ListCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/AddVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/EditVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/vms/logic/parser/CommandParser.java
  src/main/java/seedu/vms/logic/parser/FeatureParser.java
  src/main/java/seedu/vms/logic/parser/ParseResult.java
  src/main/java/seedu/vms/logic/parser/Parser.java
  src/main/java/seedu/vms/logic/parser/VmsParser.java
  src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java
  src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java
  src/main/java/seedu/vms/logic/parser/appointment/DeleteCommandParser.java
  src/main/java/seedu/vms/logic/parser/appointment/EditCommandParser.java
  src/main/java/seedu/vms/logic/parser/basic/BasicParser.java
  src/main/java/seedu/vms/logic/parser/patient/AddCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/DeleteCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/EditCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/FindCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/PatientParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaxTypeValueParser.java
  src/main/java/seedu/vms/ui/ResultDisplay.java
  src/main/java/seedu/vms/ui/ResultMessageBox.java
  src/test/java/seedu/vms/logic/commands/CommandResultTest.java
  src/test/java/seedu/vms/logic/commands/CommandTestUtil.java
  src/test/java/seedu/vms/logic/commands/basic/ExitCommandTest.java
  src/test/java/seedu/vms/logic/commands/basic/HelpCommandTest.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/AddVaxTypeTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/EditVaxTypeTest.java
  src/test/java/seedu/vms/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/vms/logic/parser/VmsParserTest.java
  src/test/java/seedu/vms/logic/parser/basic/BasicParserTest.java
  src/test/java/seedu/vms/logic/parser/patient/PatientParserTest.java
  src/test/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParserTest.java
Labels: priority.High, type.Enhancement

#214 Enable assertions
  build.gradle
Labels: priority.Medium

#210 Fix visual bugs
  src/main/java/seedu/vms/ui/ResultDisplay.java
  src/main/java/seedu/vms/ui/TagFlowView.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Low

#212 Add start up loading messages
  src/main/java/seedu/vms/MainApp.java
  src/main/java/seedu/vms/commons/util/JsonUtil.java
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: priority.Medium, type.Enhancement

#213 Update DG description for `LogicManager`
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#221 Remove custom file path from `PatientManager` I/O
  src/main/java/seedu/vms/MainApp.java
  src/main/java/seedu/vms/commons/core/Config.java
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/vms/model/UserPrefs.java
  src/main/java/seedu/vms/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/vms/storage/Storage.java
  src/main/java/seedu/vms/storage/StorageManager.java
  src/main/java/seedu/vms/storage/UserPrefsStorage.java
  src/main/java/seedu/vms/storage/patient/JsonAdaptedPatient.java
  src/main/java/seedu/vms/storage/patient/JsonAdaptedPatientData.java
  src/main/java/seedu/vms/storage/patient/JsonPatientManagerStorage.java
  src/main/java/seedu/vms/storage/patient/JsonSerializablePatientManager.java
  src/main/java/seedu/vms/storage/patient/PatientManagerStorage.java
  src/main/java/seedu/vms/ui/MainWindow.java
  src/test/java/seedu/vms/commons/core/ConfigTest.java
  src/test/java/seedu/vms/commons/util/ConfigUtilTest.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
  src/test/java/seedu/vms/model/ModelManagerTest.java
  src/test/java/seedu/vms/model/UserPrefsTest.java
  src/test/java/seedu/vms/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/vms/storage/StorageManagerTest.java
  src/test/java/seedu/vms/storage/patient/JsonAdaptedPatientTest.java
  src/test/java/seedu/vms/storage/patient/JsonPatientManagerStorageTest.java
  src/test/java/seedu/vms/storage/patient/JsonSerializablePatientManagerTest.java
Labels: priority.Medium, type.Enhancement

#226 Fix copy and paste in message box
  src/main/java/seedu/vms/ui/ResultMessageBox.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResultMessageBox.fxml
Labels: type.Bug, severity.Medium

#223 Vaccination limits
  docs/DeveloperGuide.md
  src/main/java/seedu/vms/model/vaccination/Requirement.java
  src/main/java/seedu/vms/model/vaccination/VaxChecker.java
  src/main/java/seedu/vms/model/vaccination/VaxRecordKey.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java
  src/test/java/seedu/vms/logic/commands/vaccination/AddVaxTypeTest.java
  src/test/java/seedu/vms/model/vaccination/RequirementTest.java
  src/test/java/seedu/vms/model/vaccination/VaxRecordKeyTest.java
  src/test/java/seedu/vms/model/vaccination/VaxTypeManagerTest.java
  src/test/java/seedu/vms/storage/vaccination/VaxTypeLoaderTest.java
  src/test/java/seedu/vms/testutil/TestUtil.java
  src/test/java/seedu/vms/testutil/VaxTestingUtil.java
Labels: priority.High, type.Task

#193 Implement more checks for Appointment Class
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java
  src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java
  src/main/java/seedu/vms/logic/parser/appointment/EditCommandParser.java
  src/main/java/seedu/vms/model/appointment/Appointment.java
Labels: priority.High, type.Task

#230 Vaccination find
  src/main/java/seedu/vms/commons/core/Messages.java
  src/main/java/seedu/vms/commons/util/StringUtil.java
  src/main/java/seedu/vms/logic/commands/vaccination/FilterVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/ListVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/FeatureParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/FilterVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/ListVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java
  src/main/java/seedu/vms/model/FilteredIdDataMap.java
  src/main/java/seedu/vms/model/FilteredMapView.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/test/java/seedu/vms/commons/util/StringUtilTest.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/FindVaxTypeTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: type.Story, priority.High

#238 Cascade delete skeleton
  src/main/java/seedu/vms/commons/core/ValueChange.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: priority.High, type.Task

#239 Simplified list view
  src/main/java/seedu/vms/commons/core/ValueChange.java
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/logic/commands/patient/DetailPatientCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/AddVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/DetailVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/EditVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/CliSyntax.java
  src/main/java/seedu/vms/logic/parser/patient/DetailPatientParser.java
  src/main/java/seedu/vms/logic/parser/patient/PatientParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DetailVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java
  src/main/java/seedu/vms/model/IdDataMap.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/StorageModel.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeAction.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/main/java/seedu/vms/storage/vaccination/JsonAdaptedVaxType.java
  src/main/java/seedu/vms/ui/DetailedView.java
  src/main/java/seedu/vms/ui/ListViewPanel.java
  src/main/java/seedu/vms/ui/MainWindow.java
  src/main/java/seedu/vms/ui/patient/PatientCard.java
  src/main/java/seedu/vms/ui/patient/SimplifiedPatientCard.java
  src/main/java/seedu/vms/ui/vaccination/SimplifiedVaxTypeCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/SimplifiedPatientCard.fxml
  src/main/resources/view/SimplifiedVaxTypeCard.fxml
  src/main/resources/view/VaxTypeCard.fxml
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: priority.High, type.Enhancement

#244 Fix appointment checks for no existing next appointment
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/logic/commands/appointment/EditCommand.java
Labels: type.Story, priority.Medium

#251 Fix basic commands
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/ui/MainWindow.java
Labels: type.Bug, severity.High

#245 Implement method to handle change in AppointmentManager
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/appointment/Appointment.java
  src/main/java/seedu/vms/model/appointment/AppointmentManager.java
Labels: priority.High, type.Task

#250 Add clear command for vaccination
  src/main/java/seedu/vms/logic/commands/vaccination/ClearVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/vaccination/ClearVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaccinationParser.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java
Labels: type.Story, priority.Medium

#249 Patient limits
  docs/DeveloperGuide.md
  src/main/java/seedu/vms/commons/util/AppUtil.java
  src/main/java/seedu/vms/commons/util/StringUtil.java
  src/main/java/seedu/vms/logic/parser/patient/AddCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/EditCommandParser.java
  src/main/java/seedu/vms/model/patient/Patient.java
  src/main/java/seedu/vms/model/vaccination/VaxType.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/test/java/seedu/vms/logic/parser/patient/AddCommandParserTest.java
  src/test/java/seedu/vms/logic/parser/patient/EditCommandParserTest.java
  src/test/java/seedu/vms/model/patient/PatientTest.java
  src/test/java/seedu/vms/testutil/TestUtil.java
Labels: priority.High, type.Enhancement

#256 Adds validation methods to AppointmentManager Class
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/appointment/AppointmentManager.java
Labels: priority.High, type.Task

#259 Add patient command parser
  src/main/java/seedu/vms/logic/commands/patient/ClearCommand.java
  src/main/java/seedu/vms/logic/commands/patient/DetailCommand.java
  src/main/java/seedu/vms/logic/commands/patient/DetailPatientCommand.java
  src/main/java/seedu/vms/logic/commands/patient/ListCommand.java
  src/main/java/seedu/vms/logic/parser/patient/ClearCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/DetailCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/DetailPatientParser.java
  src/main/java/seedu/vms/logic/parser/patient/ListCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/PatientParser.java
  src/test/java/seedu/vms/logic/commands/patient/DetailCommandTest.java
  src/test/java/seedu/vms/logic/parser/patient/DetailCommandParserTest.java
Labels: priority.Medium

#260 Appointment validation integration
  src/main/java/seedu/vms/commons/core/Messages.java
  src/main/java/seedu/vms/commons/exceptions/UnexpectedChangeException.java
  src/main/java/seedu/vms/commons/util/StringUtil.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/logic/commands/patient/ClearCommand.java
  src/main/java/seedu/vms/logic/commands/patient/DeleteCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/ClearVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/DeleteVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/ParserUtil.java
  src/main/java/seedu/vms/logic/parser/patient/ClearCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/DeleteCommandParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/ClearVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParser.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/StorageModel.java
  src/main/java/seedu/vms/model/appointment/AppointmentManager.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/patient/DeleteCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: priority.High, type.Task

#262 Modify vaccination detail card
  src/main/java/seedu/vms/ui/vaccination/RequirementBox.java
  src/main/java/seedu/vms/ui/vaccination/VaxTypeCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RequirementBox.fxml
  src/main/resources/view/VaxTypeCard.fxml
Labels: priority.Medium, type.Enhancement

#264 Append functionalities for edition of list like attributes
  src/main/java/seedu/vms/logic/commands/patient/EditCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/EditVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/CliSyntax.java
  src/main/java/seedu/vms/logic/parser/patient/EditCommandParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/EditVaxTypeParser.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeBuilder.java
  src/test/java/seedu/vms/testutil/SampleVaxTypeData.java
Labels: priority.Medium, type.Enhancement

#266 Fix patient detail resize bug
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Low

#272 Update headings
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Doc

#267 Implements FindCommand for the Appointment class
  src/main/java/seedu/vms/commons/core/Messages.java
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/logic/commands/appointment/FindCommand.java
  src/main/java/seedu/vms/logic/parser/CliSyntax.java
  src/main/java/seedu/vms/logic/parser/ParserUtil.java
  src/main/java/seedu/vms/logic/parser/appointment/AppointmentParser.java
  src/main/java/seedu/vms/logic/parser/appointment/FindCommandParser.java
  src/main/java/seedu/vms/model/Model.java
  src/main/java/seedu/vms/model/ModelManager.java
  src/main/java/seedu/vms/model/appointment/predicates/EndTimePredicate.java
  src/main/java/seedu/vms/model/appointment/predicates/IndexPredicate.java
  src/main/java/seedu/vms/model/appointment/predicates/StartTimePredicate.java
  src/main/java/seedu/vms/model/appointment/predicates/VaccineContainsKeywordsPredicate.java
  src/test/java/seedu/vms/logic/commands/patient/AddCommandTest.java
  src/test/java/seedu/vms/logic/commands/vaccination/VaxTypeModelStub.java
Labels: type.Story, priority.Medium

#268 Standardise error message for vaccination
  src/main/java/seedu/vms/commons/core/GuiSettings.java
  src/main/java/seedu/vms/commons/core/Messages.java
  src/main/java/seedu/vms/commons/util/StringUtil.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/logic/commands/appointment/AddCommand.java
  src/main/java/seedu/vms/logic/commands/patient/AddCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/AddVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/ParserUtil.java
  src/main/java/seedu/vms/logic/parser/vaccination/AddVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DetailVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/EditVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/VaxTypeBuilderParser.java
  src/main/java/seedu/vms/model/IdDataMap.java
  src/main/java/seedu/vms/model/vaccination/VaxTypeManager.java
  src/main/java/seedu/vms/ui/ResultMessageBox.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/vms/logic/parser/patient/EditCommandParserTest.java
Labels: priority.Medium, type.Task

#276 Enhance messages
  src/main/java/seedu/vms/MainApp.java
  src/main/java/seedu/vms/commons/core/Messages.java
  src/main/java/seedu/vms/commons/util/JsonUtil.java
  src/main/java/seedu/vms/commons/util/StringUtil.java
  src/main/java/seedu/vms/logic/Logic.java
  src/main/java/seedu/vms/logic/LogicManager.java
  src/main/java/seedu/vms/logic/commands/vaccination/DetailVaxTypeCommand.java
  src/main/java/seedu/vms/logic/commands/vaccination/ListVaxTypeCommand.java
  src/main/java/seedu/vms/logic/parser/FeatureParser.java
  src/main/java/seedu/vms/logic/parser/appointment/AddCommandParser.java
  src/main/java/seedu/vms/logic/parser/patient/AddCommandParser.java
  src/main/java/seedu/vms/ui/ResultMessageBox.java
  src/main/java/seedu/vms/ui/Ui.java
  src/main/java/seedu/vms/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RequirementBox.fxml
  src/main/resources/view/VaxTypeCard.fxml
  src/test/java/seedu/vms/logic/parser/patient/AddCommandParserTest.java
Labels: priority.High, type.Enhancement

#273 Add paitent component, cascade delete/change into dg
  docs/DeveloperGuide.md
Labels: priority.High, type.Doc

#278 Updates the Appointment Class portion of the UG
  docs/UserGuide.md
Labels: type.Doc

#254 Complete vaccination UG
  docs/UserGuide.md
  docs/images/VaccinationAddDetailCard.png
  docs/images/VaccinationDetailExample.png
  docs/images/VaccinationEditDetailCard_1.png
  docs/images/VaccinationEditDetailCard_2.png
  docs/images/VaccinationFindExample.png
  src/main/java/seedu/vms/logic/parser/vaccination/AddVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DeleteVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/DetailVaxTypeParser.java
  src/main/java/seedu/vms/logic/parser/vaccination/FilterVaxTypeParser.java
Labels: priority.High, type.Task

#284 Fix basic keyword
  src/main/java/seedu/vms/commons/core/GuiSettings.java
  src/main/java/seedu/vms/logic/parser/VmsParser.java
  src/main/java/seedu/vms/logic/parser/basic/BasicParser.java
  src/main/java/seedu/vms/ui/HelpWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.High

#285 Add check for patients with multiple appointments
  src/main/java/seedu/vms/logic/commands/appointment/UnmarkCommand.java
  src/main/java/seedu/vms/storage/appointment/JsonSerializableAppointmentManager.java
Labels: type.Bug, severity.Medium

#290 Branch update ug
  docs/UserGuide.md
Labels: priority.High, type.Doc
